openapi: 3.0.3
info:
  title: Gestión de cuentas bancarias API
  version: 1.0.0

tags:
  - name: Clientes
    description: Operaciones relacionadas con los clientes y cuentas bancarias relacionadas.

paths:
  /clientes:
    get:
      tags:
        - Clientes
      summary: Obtener todos los clientes con sus cuentas
      operationId: getCustomersAndAccounts
      responses:
        '200':
          description: Lista de todos los clientes con sus datos personales y las cuentas bancarias asociadas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomerAccount'

# TODO -> Separar componentes en otro fichero
components:
  schemas:
    BankAccountNoCustomer:
      type: object
      properties:
        accountType:
          type: string
          example: 'NORMAL'
        total:
          type: number
          format: double
          example: '1000.50'
    CustomerAccount:
      type: object
      properties:
        dni:
          type: string
          example: '00000000Z'
        name:
          type: string
          example: 'Adrián'
        surname1:
          type: string
          example: 'Torres'
        surname2:
          type: string
          example: 'Barca'
        birthDate:
          type: string
          format: date
          example: '26/09/1993'
        accounts:
          type: array
          items:
            $ref: '#/components/schemas/BankAccountNoCustomer'
