spring:
  application:
    name: banking-service
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  security:
    oauth2:
      resourceserver:
        jwt:
          # When using issuer-uri, Spring Security will not attempt to validate the token against a specific issuer;
          # this should not be done in production, but it is useful for development and testing with Keycloak.
#          issuer-uri: http://keycloak:8080/realms/banking
          jwk-set-uri: http://keycloak:8080/realms/banking/protocol/openid-connect/certs
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
      schema-locations: classpath:db/*.sql
      encoding: UTF-8
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        generate_statistics: true # Enable hibernate statistics

  # Problem detail
  mvc:
    problemdetails:
      enabled: true

  cache:
    cache-names:
      - customer-with-accounts
      - bank-accounts
      - account-types
    caffeine:
      spec: maximumSize=500,expireAfterWrite=2m,recordStats

# Application logs level
logging:
  level:
    root: INFO
    com.clientes.cuentas.bankingservice: DEBUG

# Expose actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,caches

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    url: /openapi/api-definition.yaml

# Force UTF-8 encoding on all HTTP responses
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
